USE QuizDB;
SELECT * FROM Questions;
SELECT * FROM Participants;

USE QuizDB;

INSERT INTO Questions (QInWords, ImageName, Option1, Option2, Option3, Option4, Answer) VALUES
('What does CPU stand for?', NULL, 'Central Process Unit', 'Central Processing Unit', 'Computer Personal Unit', 'Central Processor Unit', 2),
('Which language is primarily used for web development?', NULL, 'Python', 'JavaScript', 'C++', 'Java', 2),
('What does RAM stand for in computers?', NULL, 'Read Access Memory', 'Random Access Memory', 'Run Accept Memory', 'Real-time Access Memory', 2),
('Which of these is an operating system?', NULL, 'HTML', 'Linux', 'CSS', 'HTTP', 2),
('What does HTTP stand for?', NULL, 'HyperText Transfer Protocol', 'HyperText Transmission Protocol', 'HyperText Transfer Program', 'HighText Transfer Protocol', 1),
('Which company developed the Windows operating system?', NULL, 'Apple', 'Microsoft', 'Google', 'IBM', 2),
('What is the main purpose of a firewall?', NULL, 'To speed up the internet', 'To block unauthorized access', 'To store files', 'To clean viruses', 2),
('Which one is a NoSQL database?', NULL, 'MySQL', 'Oracle', 'MongoDB', 'SQL Server', 3),
('What does CSS stand for?', NULL, 'Cascading Style Sheets', 'Computer Style Sheets', 'Creative Style System', 'Colorful Style Sheets', 1),
('Which programming language is known for its use in AI and data science?', NULL, 'C#', 'Python', 'Ruby', 'PHP', 2),
('What does GPU stand for?', NULL, 'Graphics Processing Unit', 'General Processing Unit', 'Graphical Performance Utility', 'Grid Processing Unit', 1),
('Which of these is an email protocol?', NULL, 'FTP', 'SMTP', 'HTTP', 'SSH', 2),
('What is the default port for HTTP?', NULL, '21', '80', '443', '25', 2),
('Which company developed Java?', NULL, 'Microsoft', 'Sun Microsystems', 'Apple', 'IBM', 2),
('What does IDE stand for in programming?', NULL, 'Integrated Development Environment', 'Internal Data Execution', 'Integrated Data Engine', 'Interactive Debug Environment', 1),
('Which device stores permanent data?', NULL, 'RAM', 'Hard Disk', 'Cache', 'Registers', 2),
('Which language is mainly used for Android app development?', NULL, 'Java', 'Swift', 'C', 'Kotlin', 4),
('What does SQL stand for?', NULL, 'Structured Query Language', 'Sequential Query Language', 'Standard Query Language', 'Simple Query Language', 1),
('Which type of network is the Internet?', NULL, 'MAN', 'WAN', 'LAN', 'PAN', 2),
('What is the purpose of DNS?', NULL, 'Translate IP addresses to domain names', 'Translate domain names to IP addresses', 'Encrypt internet data', 'Control bandwidth', 2),
('Which is a version control system?', NULL, 'Git', 'Apache', 'MySQL', 'Nginx', 1),
('What does HTML stand for?', NULL, 'HyperText Markup Language', 'HyperText Modeling Language', 'HyperText Management Language', 'HyperText Machine Language', 1),
('Which one is an open-source operating system?', NULL, 'Linux', 'Windows', 'macOS', 'Solaris', 1),
('What does IoT stand for?', NULL, 'Internet of Things', 'Input over TCP', 'Interoperation of Technology', 'Internet of Technology', 1),
('Which cloud service is from Microsoft?', NULL, 'AWS', 'Azure', 'GCP', 'Oracle Cloud', 2),
('What is the default port for HTTPS?', NULL, '21', '25', '80', '443', 4),
('Which is a scripting language?', NULL, 'C', 'C++', 'JavaScript', 'Java', 3),
('What does API stand for?', NULL, 'Application Programming Interface', 'Application Process Integration', 'Applied Program Instruction', 'Automated Program Interface', 1),
('Which one is a primary key characteristic?', NULL, 'Can be null', 'Must be unique', 'Must be duplicate', 'Optional', 2),
('Which technology is used for containerization?', NULL, 'Docker', 'VMware', 'Hyper-V', 'Kubernetes', 1),
('What is the binary number 1010 in decimal?', NULL, '8', '9', '10', '11', 3),
('Which protocol secures data over the Internet?', NULL, 'HTTP', 'HTTPS', 'FTP', 'SMTP', 2),
('What does SaaS stand for?', NULL, 'Software as a Service', 'System as a Software', 'Storage as a Service', 'Software as a System', 1),
('Which is an example of a relational database?', NULL, 'MongoDB', 'MySQL', 'Redis', 'Cassandra', 2),
('What is Python primarily used for?', NULL, 'Data Science', 'Web Development', 'Automation', 'All of the above', 4),
('What is the main function of an operating system?', NULL, 'Manage hardware and software resources', 'Write code', 'Connect to the Internet', 'Run antivirus scans', 1),
('What does VPN stand for?', NULL, 'Virtual Private Network', 'Virtual Public Network', 'Verified Private Node', 'Virtual Process Network', 1),
('Which language is used for iOS app development?', NULL, 'Swift', 'Java', 'C#', 'Objective-C', 1),
('Which is a markup language?', NULL, 'HTML', 'CSS', 'Python', 'JavaScript', 1),
('What does LAN stand for?', NULL, 'Large Area Network', 'Local Area Network', 'Logical Area Network', 'Long Area Network', 2),
('What is GitHub mainly used for?', NULL, 'Cloud storage', 'Source code hosting', 'Video streaming', 'Database hosting', 2),
('What is an IP address used for?', NULL, 'Identifying devices on a network', 'Encrypting data', 'Storing files', 'Streaming video', 1),
('What is a compiler?', NULL, 'Program that translates code to machine language', 'Program that runs code directly', 'Hardware device', 'Database system', 1),
('What is the extension for a C# source file?', NULL, '.cpp', '.c', '.cs', '.java', 3),
('Which company developed C#?', NULL, 'Microsoft', 'Google', 'Apple', 'IBM', 1),
('Which is a cloud storage service?', NULL, 'Dropbox', 'Visual Studio', 'Slack', 'Trello', 1),
('What is two-factor authentication?', NULL, 'Two passwords', 'Two-step verification process', 'Two usernames', 'Two devices', 2),
('Which database is from Microsoft?', NULL, 'Oracle', 'MySQL', 'SQL Server', 'PostgreSQL', 3),
('What does SMTP stand for?', NULL, 'Simple Mail Transfer Protocol', 'Secure Mail Transfer Protocol', 'Standard Mail Transfer Protocol', 'Send Mail Transfer Protocol', 1),
('What does AI stand for?', NULL, 'Artificial Intelligence', 'Automated Information', 'Applied Integration', 'Artificial Integration', 1);

SELECT * FROM Questions;